### ISSUE TITLE
Best approach to mock functions after require_once.

### ISSUE THREAD

**Issue by aaronfc** [Brain-WP/BrainMonkey#137]
Hey,
I have been using BrainMonkey recently (thanks for it!).

I have the following piece of code at the end of a method I want to cover with unit tests:
```php
// ...
require_once ABSPATH . 'wp-admin/includes/upgrade.php';
dbDelta( $sql );
// ...
```

In the test I am adding this expectation:
```php
Functions\expect( 'dbDelta' )->once();
```

I think it's quite common to have some WP methods that require an explicit `require_once` (because they are not loaded by default, like in [this case](https://codex.wordpress.org/Creating_Tables_with_Plugins#Creating_or_Updating_the_Table)).

At the moment I am extracting that piece of code into a separate function (under my namespace) and then I am just using this method from my original code and patching it in the test. But I was wondering if there is any better alternative?

This is my current approach:
functions.php
```php
namespace Aaron;

function dbDelta() {
  require_once ABSPATH . 'wp-admin/includes/upgrade.php';
  \dbDelta( $sql );
}
```

code.php
```php
\Aaron\dbDelta( $sql );
```

test.php
```php
Functions\expect( 'Aaron\dbDelta )->once();
```

**Comment by gmazzap** [comment]
Hi @aaronfc 

Writing a wrapper for functions to mock is not an uncommon practice, especially for projects like WordPress code that do not implement autoloading for objects and make large use of functions (not auto-loadable).

There are people who advocate _always_ doing it, and that popularized a saying [_"Don’t Mock What You Don’t Own"_](https://www.google.com/search?q=Don%E2%80%99t+Mock+What+You+Don%E2%80%99t+Own&rlz=1C1CHBF_itIT998IT998&oq=Don%E2%80%99t+Mock+What+You+Don%E2%80%99t+Own&aqs=chrome.0.69i59j0i22i30l3j69i60l2.349j0j4&sourceid=chrome&ie=UTF-8) (a concept which, I _think_ was first introduced in this paper: http://jmock.org/oopsla2004.pdf).

Regardless you agree or not with that idea, doing it in your specific case, does not seem too bad to me.

An alternative you might consider is to change your code to:

```php
// ...
if  ( defined('ABSPATH') && ! function_exists('dbDelta')) {
    require_once ABSPATH . 'wp-admin/includes/upgrade.php';
}
dbDelta( $sql );
// ...
```

It works because when you let Brain Monkey mock the function, it'll declare the function for you, so the condition will always be `false`, even assuming you define `ABSPATH` in our tests.

Sure, `function_exists` adds some overhead to the execution, but considering I'm not expecting you're calling this code on every request and surely (I hope) in nothing "performance critical", then you might be okay in this teeny tiny overhead.

Please note: I'm not saying this is _better_ or _worse_ approach, it's just another approach.

**Comment by aaronfc** [comment]
Thanks for the detailed answer :)
