### ISSUE TITLE
Detecting closure for add_filter

### ISSUE THREAD

**Issue by GaryJones** [Brain-WP/BrainMonkey#29]
As a simple case, I've got:

```php
add_filter( 'foo', function() {
	return '';
});
```
in a method.

When I call that method in my test, my assertion is:
```php
static::assertTrue( has_filter( 'foo', 'function ()' ) );
```
...as this is how the [docs](https://github.com/Brain-WP/BrainMonkey/blob/1e3d7a92968d110b5c82ab55b8d74f0a15aa00fd/docs/wordpress-hooks-added.md#identify-closures) say to do it.

The test fails however with a simple `Failed asserting that false is true.`

I've got another test in the same file, also using `has_filter()`, which suitably passes or fails when detecting a class method call.

What's the trick here?

BrainMonkey 1.4.2

----
The actual code I want to test is:

```php
foreach ( $this->config->getArrayCopy() as $key => $value ) {
	add_filter( "genesis_pre_get_option_{$key}", function () use ( $value ) {
		return $value;
	} );
}
```

**Comment by GaryJones** [comment]
Works in BM 2, so I guess this just wasn't supported in BM 1.4.

**Comment by gmazzap** [comment]
@GaryJones The docs you are pointing are for version 2+, but the cose should work for v1.4.2 as well.

In v 1.* closures are all serialized to the string `"function()"` whereas in version 2 it is possbile to distinguish by closure arguments. But not having any arguments you test should not differ between the 2 version.

The issue is that in version 2.* the closure string form does not care about spaces, but in version 1 the string `"function()"` must be written exactly like that. 

So your test will work if you use

```php
static::assertTrue( has_filter( 'foo', 'function()' ) );
```

I'm reopening as it makes sense that in vversion 1.4.2 both `'function()'` and `'function ()'` are accepted.

**Comment by GaryJones** [comment]
OK - the docs (v2) include the space, but it isn't clear whether this was required like that or not.

**Comment by gmazzap** [comment]
In v2, spaces are not an issue. So in v2 you already use `function ()` and `function()`. I could mention that spaces are irrelevant.

I just checked and in v1 docs, the string was without spaces.

FIY There's a `version/1` branch on the repo that contains last code for that series. You can look at [`/docs` folder there](https://github.com/Brain-WP/BrainMonkey/blob/version/1/docs/), for a reference on v1 series, considering that GitHub pages does not allow for different version of the websites.

**Comment by gmazzap** [comment]
With d91ea9d `function()` can be used in v1.* with spaces anywhere and still valid, live in version 2.*. Will close when 1.4.3 will be out.

**Comment by gmazzap** [comment]
Done in v1.5.0.

Spaces are no more relevant: `function()`, and  `function ( )` are both valid now; actually anything matching `^\s*function\s*\(\s*\)\s*$` is valid.
