### ISSUE TITLE
"This test did not perform any assertions" warning when using Actions\expectDone in test

### ISSUE THREAD

**Issue by chesio** [Brain-WP/BrainMonkey#39]
Hi,

I have set up a test case following the documentation at https://brain-wp.github.io/BrainMonkey/docs/wordpress-hooks-done.html#test-fired-hooks-with-expectations - my test case is almost identical to the example provided in docs.

I noticed that when the test fails, there's an error reported, but when it passes, PHPUnit (I'm using version 6.5.7) complains about it being risky: "This test did not perform any assertions".

Is this expected behavior?

**Comment by tfrommen** [comment]
This is because you did not integrate Mockery (which is used under the hood) and PHPUnit.

You can do this by adding the following trait to your (base) test case class:

```php
class MyTest extends MyTestCase {

    use \Mockery\Adapter\Phpunit\MockeryPHPUnitIntegration;

    /* ... */
}
```

This has been discussed before (on Twitter), and I thought the result was that this should be documented somewhere. Brain Monkey will most probably not take care of this kind of integration, because it is specific to PHPUnit (althoug Brain Monkey itself if framework-anostic).

**Comment by chesio** [comment]
Hi Thorsten,

Thanks, your suggestion fixed the problem!

It seems this has been already documented (in 7a5b4ce8d000090bdc6cdb193ea3045a86b0d5ad), but the [online docs](https://brain-wp.github.io/BrainMonkey/docs/wordpress-setup.html) have not been updated since.
